### ISSUE TITLE
CR10 - MENU MANAGEMENT

### ISSUE THREAD

**Issue by norhusna** [norhusna/Change-Request#10]
Unable to add category in the menu management

**Comment by puterinorliana** [comment]
![image](https://user-images.githubusercontent.com/70568386/116860719-926fa800-ac34-11eb-9878-fb483f773568.png)


![image](https://user-images.githubusercontent.com/70568386/116860744-9dc2d380-ac34-11eb-8477-c6ba9d6a7423.png)

**Comment by puterinorliana** [comment]
<?php
	
	//Add new menu (category)
	if (isset($_POST['addmenu'])) {

		if (!empty($_POST['menuname'])) {
			$menuname = $sqlconnection->real_escape_string($_POST['menuname']);

			$addMenuQuery = "INSERT INTO tbl_menu (menuName) VALUES ('{$menuname}')";

			if ($sqlconnection->query($addMenuQuery) === TRUE) {
				header("Location: menu.php");
			} else {
				//handle
				echo "someting wong";
			}
		}

		//No input handle
		else {
			echo "...";
		}

	}


?>

**Comment by norhusna** [comment]
the change request has been completed and the issues will be closed
