### ISSUE TITLE
CR5 - UPDATE STAFF STATUS (ONLINE/OFFLINE) 

### ISSUE THREAD

**Issue by norhusna** [norhusna/Change-Request#5]
Admin does not aware other staff status and role in the restaurant

**Comment by puterinorliana** [comment]
![image](https://user-images.githubusercontent.com/70568386/116859227-3b68d380-ac32-11eb-82fc-ba83190358df.png)

**Comment by puterinorliana** [comment]
<?php

  include("../functions.php");

  if((!isset($_SESSION['uid']) && !isset($_SESSION['username']) && isset($_SESSION['user_level'])) ) 
    header("Location: login.php");

  if($_SESSION['user_level'] != "staff")
    header("Location: login.php");


	if (isset($_POST['btnStatus']) && isset($_POST['staffid'])) {

		$btnStatus = $sqlconnection->real_escape_string($_POST['btnStatus']);
		$staffID = $sqlconnection->real_escape_string($_POST['staffid']);

		if ($btnStatus== "Online")
			$status = "Offline";

		if ($btnStatus== "Offline")
			$status = "Online";
		
		$addOrderQuery = "UPDATE tbl_staff SET status = '{$status}' WHERE staffID = {$staffID};";

		if ($sqlconnection->query($addOrderQuery) === TRUE) {
				header("Location: index.php");
			} 

		else {
				//handle
				echo "someting wong";
				echo $sqlconnection->error;

		}
	}
?>

**Comment by puterinorliana** [comment]
<?php

  include("../functions.php");

  if((!isset($_SESSION['uid']) && !isset($_SESSION['username']) && isset($_SESSION['user_level'])) ) 
    header("Location: login.php");

  if($_SESSION['user_level'] != "staff")
    header("Location: login.php");


	if (isset($_POST['btnStatus']) && isset($_POST['staffid'])) {

		$btnStatus = $sqlconnection->real_escape_string($_POST['btnStatus']);
		$staffID = $sqlconnection->real_escape_string($_POST['staffid']);

		if ($btnStatus== "Online")
			$status = "Offline";

		if ($btnStatus== "Offline")
			$status = "Online";
		
		$addOrderQuery = "UPDATE tbl_staff SET status = '{$status}' WHERE staffID = {$staffID};";

		if ($sqlconnection->query($addOrderQuery) === TRUE) {
				header("Location: index.php");
			} 

		else {
				//handle
				echo "someting wong";
				echo $sqlconnection->error;

		}
	}
?>

**Comment by norhusna** [comment]
this change request  CR has been completed and the issue will be closed
