### ISSUE TITLE
CR9 - MANAGE PRICE 

### ISSUE THREAD

**Issue by norhusna** [norhusna/Change-Request#9]
Unable to delete the prices of the food

**Comment by puterinorliana** [comment]
![image](https://user-images.githubusercontent.com/70568386/116860602-648a6380-ac34-11eb-84a1-ad977aa78c3e.png)

**Comment by puterinorliana** [comment]
<?php

	include("../functions.php");

	if((!isset($_SESSION['uid']) && !isset($_SESSION['username']) && isset($_SESSION['user_level'])) ) 
		header("Location: login.php");

	if($_SESSION['user_level'] != "admin")
		header("Location: login.php");

	if(isset($_POST['btnedit'])) {

		if (!empty($_POST['itemName']) && !empty($_POST['itemPrice']) ) {

			$menuID = $sqlconnection->real_escape_string($_POST['menuID']);
			$itemID = $sqlconnection->real_escape_string($_POST['itemID']);
			$itemName = $sqlconnection->real_escape_string($_POST['itemName']);
			$itemPrice = $sqlconnection->real_escape_string($_POST['itemPrice']);

			$updateItemQuery = "UPDATE tbl_menuitem SET menuItemName = '{$itemName}' , price = {$itemPrice} WHERE menuID = {$menuID} AND itemID = {$itemID} ";

			if ($sqlconnection->query($updateItemQuery) === TRUE) {
				header("Location: menu.php"); 
				exit();
			} 

			else {
				//handle
				echo "someting wong";
				echo $sqlconnection->error;
				echo $updateItemQuery;
			}

		}
	} 

?>

**Comment by norhusna** [comment]
change request has been completed
